AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProdPrivateSubnetId: {Type: String}
  AnalyticsVpcId: {Type: String}
  AnalyticsSubnetId: {Type: String}
Resources:
  PrivateLinkNLB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: PrivateLinkNLB
      Type: network
      Subnets: [!Ref ProdPrivateSubnetId]
  EndpointService:
    Type: 'AWS::EC2::VPCEndpointService'
    Properties:
      NetworkLoadBalancerArns: [!Ref PrivateLinkNLB]
      AcceptanceRequired: true
  InterfaceEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcId: !Ref AnalyticsVpcId
      ServiceName: !Ref EndpointService
      VpcEndpointType: Interface
      SubnetIds: [!Ref AnalyticsSubnetId]
